easy_admin:
  entities:
    User:
      class: App\Entity\User
    Categories:
      class: App\Entity\Categories
    Recette:
      class: App\Entity\Recette
      form:
          fields:
            - title
            - content
            - nbViews
            - imageAlt
            - likes
            - user
            - comment
            - categories
            -
                  property: ImageFile
                  type: "file"




