fos_user:
  db_driver: orm # valid values are 'orm', 'mongodb' and 'couchdb'
  user_class: App\Entity\User
  firewall_name: main
  service:
    mailer: fos_user.mailer.noop
  from_email:
    address: "fatima"
    sender_name: "fatimaaaa"